version: '3.8'

services:
  iti_database_s :
    image : mcr.microsoft.com/mssql/server:2022-latest
    container_name : iti_database
    environment : 
      MSSQL_SA_PASSWORD: 'Hamada1020'
      ACCEPT_EULA: 'Y'
    ports:
      - '1433:1433'
  iti_backend : 
    image : iti
    container_name : iti_c
    build :
      context : .
      dockerfile : Dockerfile
    ports : 
      - "8080:8080"
    volumes :  
      - iti:/app

volumes:
  iti:

